
INSERT INTO yatish_client (name) VALUES
  ('EduNat'),
  ('EIF');
INSERT INTO yatish_task (name) VALUES
  ('Accounting'),
  ('Business (devel.)'),
  ('Data'),
  ('Development (IT)'),
  ('Development (R&D)'),
  ('Model'),
  ('Report'),
  ('Reporting-ERP'),
  ('Research (R&D)'),
  ('Sysadmin'),
  ('Webadmin'),
  ('(auto)formation'),
  ('admin/organi'),
  ('analyse/synthèse'),
  ('coordi'),
  ('coordImp'),
  ('évaluation'),
  ('inclusion'),
  ('maths-sciences'),
  ('parents'),
  ('présentiel'),
  ('suivi stage'),
  ('vie sco');
INSERT INTO yatish_tool (name) VALUES
  (' '),
  ('AWS/EC2'),
  ('Bash/awk/gnuplot'),
  ('Basilisk'),
  ('Blender'),
  ('C/C++/SQL'),
  ('CodeBlocks&co.'),
  ('Dokuwiki'),
  ('Drupal&co.'),
  ('Grass'),
  ('Subversion'),
  ('Swat'),
  ('Windows'),
  ('AP'),
  ('CI'),
  ('CO'),
  ('conseil'),
  ('maths'),
  ('sciences'),
  ('surveillance'),
  ('bureautique/images'),
  ('calculatrices'),
  ('chariot/labo/ordis'),
  ('ChingView'),
  ('copies/cahiers'),
  ('courriel'),
  ('GeoGebra'),
  ('papier-crayon-notes'),
  ('photocop/papeterie'),
  ('PIX'),
  ('Pronote'),
  ('Pyromaths'),
  ('Quizinière'),
  ('réunion-RdV'),
  ('SACoche'),
  ('tél.'),
  ('tice/multimédia'),
  ('YATiSh'),
  ('web/pdf/books');
INSERT INTO yatish_project (name,client_id) VALUES
  ('DDL29',1),
  ('CCF',1),
  ('TrocAsio',1),
  ('Sgen',1),
  ('Portfolio',2),
  ('Yatish',2),
  ('BasilCloud',2),
  ('Drupal10',2);
/*INSERT INTO yatish_timeslot (start,stop,activity_id) VALUES
  ('2020-02-19 09:30:00','2020-02-19 10:45:00',1),
  ('2020-02-19 11:15:00','2020-02-19 13:20:00',2);
SELECT sum(round((unix_timestamp(stop)-unix_timestamp(start))/3600.,1))
  FROM yatish_timeslot GROUP BY activity_id;*/
